"""
medeval/models/anthropic_connector.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Anthropic Messages API model connector.

Provides direct support for Anthropic Claude models (e.g., claude-3-5-sonnet-20241022,
claude-3-opus-20240229, claude-3-haiku-20240307) using the official ``anthropic`` SDK.

Note:
    Anthropic's API does not currently expose token log-probabilities.
    ``generate_probabilities()`` returns an empty list, allowing downstream metrics
    (Accuracy, Hallucination Rate, Safety Audit) to compute cleanly while safely
    omitting logprob-dependent calibration metrics (ECE/MCE).
"""

from __future__ import annotations

import logging
import os
from typing import Any

from .base import BaseModelConnector

logger = logging.getLogger(__name__)


class AnthropicConnector(BaseModelConnector):
    """Connector for the Anthropic Messages API.

    Loads the ``anthropic`` library lazily on first invocation.

    Args:
        model_name: The Anthropic model identifier (e.g., 'claude-3-5-sonnet-20241022').
        api_key: The Anthropic API key. If not provided, checks ``ANTHROPIC_API_KEY``, ``AGENTROUTER_API_KEY``, etc.
        base_url: Optional API base URL override.
        max_tokens: Maximum tokens to generate per response. Defaults to 1024.
        client_kwargs: Additional arguments passed to ``anthropic.Anthropic()``.
    """

    def __init__(
        self,
        model_name: str,
        api_key: str | None = None,
        base_url: str | None = None,
        max_tokens: int = 1024,
        client_kwargs: dict[str, Any] | None = None,
    ) -> None:
        """Initialise Anthropic API credentials and target model configuration."""
        super().__init__(model_name=model_name)
        self._api_key = api_key
        self._base_url = base_url
        self._max_tokens = max_tokens
        self._client_kwargs = client_kwargs or {}
        self._client: Any = None

    def _lazy_init(self) -> None:
        """Lazily imports and instantiates the Anthropic client."""
        if self._client is not None:
            return

        try:
            import anthropic  # type: ignore[import-untyped,import-not-found] # noqa: PLC0415
        except ImportError as exc:
            raise ImportError(
                "The 'anthropic' package is required for AnthropicConnector. "
                "Install it with: pip install anthropic"
            ) from exc

        api_key = (
            self._api_key
            or os.environ.get("ANTHROPIC_API_KEY")
            or os.environ.get("AGENTROUTER_API_KEY")
            or os.environ.get("OPENROUTER_API_KEY")
        )
        base_url = (
            self._base_url
            or os.environ.get("ANTHROPIC_BASE_URL")
            or os.environ.get("AGENTROUTER_ANTHROPIC_BASE_URL")
            or os.environ.get("AGENTROUTER_BASE_URL")
        )

        kwargs = dict(self._client_kwargs)
        if api_key and "api_key" not in kwargs and "auth_token" not in kwargs:
            kwargs["api_key"] = api_key
        if base_url and "base_url" not in kwargs:
            kwargs["base_url"] = base_url

        self._client = anthropic.Anthropic(**kwargs)

    def generate(self, prompt: str) -> str:
        """Query the Anthropic Messages API for a textual prediction.

        Args:
            prompt: Text prompt to feed into the model.

        Returns:
            The textual response generated by Claude.
        """
        self._lazy_init()
        assert self._client is not None

        response = self._client.messages.create(
            model=self.model_name,
            max_tokens=self._max_tokens,
            messages=[{"role": "user", "content": prompt}],
        )

        if isinstance(response, str):
            return response.strip()

        parts: list[str] = []
        if hasattr(response, "content") and response.content:
            for block in response.content:
                if isinstance(block, str):
                    parts.append(block)
                elif hasattr(block, "text"):
                    parts.append(str(block.text))
        return "".join(parts).strip()

    def generate_probabilities(self, prompt: str) -> list[float]:  # noqa: ARG002
        """Return log-probabilities for the generated response.

        Note:
            Anthropic API does not expose token log-probabilities. This method logs
            a warning and returns an empty list, allowing downstream evaluation
            to omit calibration metrics (ECE/MCE) without failing.

        Args:
            prompt: Input text prompt.

        Returns:
            Empty list [].
        """
        logger.warning(
            "Anthropic API does not expose token log-probabilities for model %s. "
            "Calibration metrics (ECE/MCE/Brier) will be omitted.",
            self.model_name,
        )
        return []
