"""
medeval/models/anthropic_connector.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Anthropic Messages API model connector.

Provides direct support for Anthropic Claude models (e.g., claude-3-5-sonnet-20241022,
claude-3-opus-20240229, claude-3-haiku-20240307) using the official ``anthropic`` SDK.

Note:
    Anthropic's API does not currently expose token log-probabilities.
    ``generate_probabilities()`` returns an empty list, allowing downstream metrics
    (Accuracy, Hallucination Rate, Safety Audit) to compute cleanly while safely
    omitting logprob-dependent calibration metrics (ECE/MCE).
"""

from __future__ import annotations

import logging
import os
from typing import Any

from .base import BaseModelConnector

logger = logging.getLogger(__name__)


class AnthropicConnector(BaseModelConnector):
    """Connector for the Anthropic Messages API.

    Loads the ``anthropic`` library lazily on first invocation.

    Args:
        model_name: The Anthropic model identifier (e.g., 'claude-3-5-sonnet-20241022').
        api_key: The Anthropic API key. If not provided, checks ``ANTHROPIC_API_KEY``, ``AGENTROUTER_API_KEY``, etc.
        base_url: Optional API base URL override.
        max_tokens: Maximum tokens to generate per response. Defaults to 2048.
        client_kwargs: Additional arguments passed to ``anthropic.Anthropic()``.
    """

    def __init__(
        self,
        model_name: str,
        api_key: str | None = None,
        base_url: str | None = None,
        max_tokens: int = 2048,
        thinking_budget: int | None = 1024,
        client_kwargs: dict[str, Any] | None = None,
    ) -> None:
        """Initialise Anthropic API credentials and target model configuration."""
        super().__init__(model_name=model_name, max_tokens=max_tokens)
        self._api_key = api_key
        self._base_url = base_url
        self._thinking_budget = thinking_budget
        self._client_kwargs = client_kwargs or {}
        self._client: Any = None

    def _lazy_init(self) -> None:
        """Lazily imports and instantiates the Anthropic client."""
        if self._client is not None:
            return

        try:
            import anthropic  # type: ignore[import-untyped,import-not-found] # noqa: PLC0415
        except ImportError as exc:
            raise ImportError(
                "The 'anthropic' package is required for AnthropicConnector. "
                "Install it with: pip install anthropic"
            ) from exc

        api_key = (
            self._api_key
            or os.environ.get("ANTHROPIC_API_KEY")
            or os.environ.get("AGENTROUTER_API_KEY")
            or os.environ.get("OPENROUTER_API_KEY")
        )
        base_url = (
            self._base_url
            or os.environ.get("ANTHROPIC_BASE_URL")
            or os.environ.get("AGENTROUTER_ANTHROPIC_BASE_URL")
            or os.environ.get("AGENTROUTER_BASE_URL")
        )

        kwargs = dict(self._client_kwargs)
        if api_key and "api_key" not in kwargs and "auth_token" not in kwargs:
            kwargs["api_key"] = api_key
        if base_url and "base_url" not in kwargs:
            kwargs["base_url"] = base_url

        self._client = anthropic.Anthropic(**kwargs)

    def generate(self, prompt: str, temperature: float = 0.0) -> str:  # noqa: ARG002
        """Query the Anthropic Messages API for a textual prediction.

        Args:
            prompt: Text prompt to feed into the model.
            temperature: The sampling temperature. Defaults to 0.0 (greedy). (Ignored for Anthropic)

        Returns:
            The textual response generated by Claude.
        """
        self._lazy_init()
        assert self._client is not None

        # Anthropic has deprecated the temperature parameter
        kwargs = {
            "model": self.model_name,
            "max_tokens": self.max_tokens,
            "messages": [{"role": "user", "content": prompt}],
        }

        if self._thinking_budget:
            # max_tokens must be strictly greater than budget_tokens
            max_tokens_val = int(str(kwargs.get("max_tokens", 2048)))
            if max_tokens_val <= self._thinking_budget:
                kwargs["max_tokens"] = self._thinking_budget + 1024

            kwargs["thinking"] = {"type": "enabled", "budget_tokens": self._thinking_budget}

        response = self._client.messages.create(**kwargs)

        if isinstance(response, str):
            return response.strip()

        parts: list[str] = []
        if hasattr(response, "content") and response.content:
            for block in response.content:
                if isinstance(block, str):
                    parts.append(block)
                elif getattr(block, "type", "") == "thinking" and hasattr(block, "thinking"):
                    # Wrap native thinking blocks in <think> tags for our CoTUncertaintyScorer
                    parts.append(f"<think>\n{block.thinking}\n</think>\n")
                elif hasattr(block, "text"):
                    parts.append(str(block.text))
        return "".join(parts).strip()

    def generate_probabilities(self, prompt: str) -> list[float]:  # noqa: ARG002
        """Return log-probabilities for the generated response.

        Note:
            Anthropic API does not expose token log-probabilities. This method logs
            a warning and returns an empty list, allowing downstream evaluation
            to omit calibration metrics (ECE/MCE) without failing.

        Args:
            prompt: Input text prompt.

        Returns:
            Empty list [].
        """
        logger.warning(
            "Anthropic API does not expose token log-probabilities for model %s. "
            "Calibration metrics (ECE/MCE/Brier) will be omitted.",
            self.model_name,
        )
        return []

    def generate_n(self, prompt: str, n: int, temperature: float = 0.7) -> list[str]:
        """Generate N independent responses for self-consistency sampling.

        Since Anthropic models may have temperature and top_p disabled in strict
        proxy environments, this overrides the default behavior to use Prompt
        Perturbation. By appending distinct structural hints to the prompt, it forces
        a deterministic model to take different reasoning paths, enabling reliable
        self-consistency sampling without relying on temperature.

        Args:
            prompt: The formatted query string sent to the model.
            n: The number of responses to sample.
            temperature: Ignored.

        Returns:
            A list of N generated response strings.
        """
        perturbations = [
            "",  # Original prompt
            "\n\nPlease think step-by-step.",
            "\n\nReview the options carefully before answering.",
            "\n\nLet's work this out in a step by step way to be sure we have the right answer.",
            "\n\nTake a deep breath and reason through this carefully.",
        ]

        results = []
        for i in range(n):
            suffix = perturbations[i % len(perturbations)]
            perturbed_prompt = prompt + suffix
            results.append(self.generate(perturbed_prompt, temperature))
        return results
