"""
medeval/models/openai_connector.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OpenAI API model connector.

Provides support for API-driven model evaluations (e.g. gpt-4o, gpt-3.5-turbo).
Exposes generation and token probability retrieval via logprobs.
"""

from __future__ import annotations

import logging
import math
import os
from typing import Any

from .base import BaseModelConnector

logger = logging.getLogger(__name__)


class OpenAIConnector(BaseModelConnector):
    """Connector for the OpenAI ChatCompletion API.

    Loads the ``openai`` library and client lazily on first invocation.

    Args:
        model_name: The OpenAI model version string (e.g., 'gpt-4o', 'gpt-3.5-turbo').
        api_key: The OpenAI API key. If not provided, the ``OPENAI_API_KEY``
            environment variable is used.
        client_kwargs: Additional configuration parameters passed to the
            ``openai.OpenAI`` constructor.
    """

    def __init__(
        self,
        model_name: str,
        api_key: str | None = None,
        client_kwargs: dict[str, Any] | None = None,
    ) -> None:
        """Initialise client credentials and target model configuration."""
        super().__init__(model_name=model_name)
        self._api_key = api_key
        self._client_kwargs = client_kwargs or {}
        self._client: Any = None

    def _lazy_init(self) -> None:
        """Lazily imports and instantiates the OpenAI client."""
        if self._client is not None:
            return

        try:
            import openai  # noqa: PLC0415
        except ImportError as exc:
            raise ImportError(
                "The 'openai' package is required for OpenAIConnector. "
                "Install it with: pip install openai"
            ) from exc

        api_key = self._api_key or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            logger.warning(
                "No API key provided or found in environment (OPENAI_API_KEY). "
                "API calls will fail unless an alternative client setup is configured."
            )

        self._client = openai.OpenAI(api_key=api_key, **self._client_kwargs)

    def generate(self, prompt: str) -> str:
        """Query the ChatCompletion API for a textual prediction.

        Args:
            prompt: Text prompt to feed into the model.

        Returns:
            The textual response generated by the model.
        """
        self._lazy_init()
        assert self._client is not None

        response = self._client.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
        )
        return str(response.choices[0].message.content).strip()

    def generate_probabilities(self, prompt: str) -> list[float]:
        """Request log-probabilities from the API and convert to linear probabilities.

        Args:
            prompt: The formatted input string.

        Returns:
            A list of float probabilities (0.0 to 1.0) for the generated response tokens.
        """
        self._lazy_init()
        assert self._client is not None

        # Request completions with logprobs enabled
        response = self._client.chat.completions.create(
            model=self.model_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.0,
            logprobs=True,
            top_logprobs=5,
        )

        choice = response.choices[0]
        if not choice.logprobs or not choice.logprobs.content:
            logger.warning("No logprobs returned by OpenAI API for model %s.", self.model_name)
            return []

        probabilities: list[float] = []
        # Extract linear probabilities from the log probabilities of generated tokens
        for token_logprob in choice.logprobs.content:
            logprob = token_logprob.logprob
            # Convert logprob (natural log) to linear probability
            linear_prob = math.exp(logprob)
            probabilities.append(linear_prob)

        return probabilities
