# medeval/structures.py
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any

@dataclass(frozen=True)
class MedicalEvalSample:
    """
    The atomic data structure for a single medical evaluation case.
    Using frozen=True makes the sample immutable, ensuring evaluation integrity.
    """
    id: str
    question: str
    ground_truth: str
    model_prediction: str
    # Softmax probabilities or logprobs from the model for calibration checks
    prediction_probabilities: Optional[List[float]] = None 
    # Metadata for filtering (e.g., 'sickle_cell', 'cardiology', 'usmle')
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class EvaluationReport:
    """Holds the macro-level evaluation metrics generated by the framework."""
    framework_version: str
    model_name: str
    total_samples: int
    metrics: Dict[str, float] = field(default_factory=dict)
    safety_violations: List[Dict[str, Any]] = field(default_factory=list)